name: Continuous Deployment

# Run this action when PRs targeting `main` are closed.
on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    # Only run if the PR was merged.
    if: ${{ github.event.pull_request.merged == true }}

    environment: github-pages

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip

      - name: Install Dependencies
        id: install
        run: |
          pip install poetry
          poetry install

      - name: Set up Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        id: deploy
        run: |
          poetry run mkdocs gh-deploy --force --theme material

      # Get the version and update the tags to use in the release
      - name: Tag Commit
        id: tag-commit
        uses: issue-ops/semver@v0.1.0
        with:
          manifest-path: pyproject.toml
          workspace: ${{ github.workspace }}
          ref: main

      # Use the version output from the previous step for the release
      # Prepend a 'v' to the beginning (e.g. 'v1.2.3')
      - name: Create Release
        id: create-release
        uses: issue-ops/releaser@main
        with:
          tag: v${{ steps.tag-commit.outputs.version }}
