version: '3'

services:
  # Python App
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 3-bullseye
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db
    user: vscode

  # PostgreSQL Database
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
