name: 2.2 Package Delivery Artifacts & Create Release

on:
  push:
    tags:
      - "*-release"
  workflow_dispatch: {}

permissions:
  contents: write

env:
  CI: true
  SITE_DIR: site

jobs:
  package-delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Site
        run: |
          # python -m mkdocs build --clean --strict --verbose --site-dir '${{ env.SITE_DIR }}'
          python -m mkdocs build --clean --verbose --site-dir '${{ env.SITE_DIR }}'
      - name: Archive Site
        run: |
          zip -r ${{ env.SITE_DIR }}.zip ${{ env.SITE_DIR }}
      - run: |
          echo "Site directory ${{ env.SITE_DIR }} content:"
          ls -al ${{ env.SITE_DIR }}

      - uses: actions/create-github-app-token@v1
        id: generate-app-token
        with:
          app-id: ${{ vars.APP_ID_ACTIONS_ASSISTANT }}
          private-key: ${{ secrets.APP_PRIVATE_KEY_ACTIONS_ASSISTANT }}

      - name: Draft release
        uses: actions/github-script@v6
        id: draft-release
        with:
          github-token: ${{ steps.generate-app-token.outputs.token }}
          script: |

            const response = await github.request(
              'POST /repos/{owner}/{repo}/releases',
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                draft: true,
                tag_name: '${{ github.ref }}',
                discussion_category_name: 'announcements',
                generate_release_notes: true,
                make_latest: 'legacy',
                headers: {
                  'X-GitHub-Api-Version': '2022-11-28'
                }
              }
            );

            console.dir(response);

            return response.data.id;

      - name: Upload release asset
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.generate-app-token.outputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.draft-release.outputs.result }}/assets?name=${{ env.SITE_DIR }}.zip" \
            --data-binary "@${{ env.SITE_DIR }}.zip"

      - name: Publish release
        uses: actions/github-script@v6
        id: publish-release
        with:
          github-token: ${{ steps.generate-app-token.outputs.token }}
          script: |

            const response = await github.request(
              'PATCH /repos/{owner}/{repo}/releases/{release_id}',
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: ${{ steps.draft-release.outputs.result }},
                draft: false,
                discussion_category_name: 'announcements',
                make_latest: 'true',
                headers: {
                  'X-GitHub-Api-Version': '2022-11-28'
                }
              }
            );

            console.dir(response);
