- name: Get new version number
  id: get_new_version
  run: |
    major=$(echo $last_version | cut -d. -f1)
    minor=$(echo $last_version | cut -d. -f2)
    patch=$(echo $last_version | cut -d. -f3)

    new_patch=$((patch+1))

    new_version="$major.$minor.$new_patch"

    echo "New version is $new_version"
    echo "new_version=$new_version" >> "$GITHUB_OUTPUT"
  env:
    last_version: ${{ steps.get_last_version.outputs.last_version }}
