name: 2.2 Package Delivery Artifacts & Create Release

on:
  push:
    tags:
      - "*-release"
  workflow_dispatch: {}

permissions:
  contents: write

env:
  CI: true
  SITE_DIR: site

jobs:
  package-delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Site
        run: |
          # python -m mkdocs build --clean --strict --verbose --site-dir '${{ env.SITE_DIR }}'
          python -m mkdocs build --clean --verbose --site-dir '${{ env.SITE_DIR }}'
      - name: Archive Site
        run: |
          zip -r ${{ env.SITE_DIR }}.zip ${{ env.SITE_DIR }}
      - run: |
          echo "Site directory ${{ env.SITE_DIR }} content:"
          ls -al ${{ env.SITE_DIR }}

      - uses: actions/create-github-app-token@v1
        id: generate-app-token
        with:
          app-id: ${{ vars.APP_ID_ACTIONS_ASSISTANT }}
          private-key: ${{ secrets.APP_PRIVATE_KEY_ACTIONS_ASSISTANT }}
