name: Run Checks

on:
  pull_request:
    branches:
      - main
  workflow_call: {}

permissions:
  actions: write
  contents: read
  security-events: write

env:
  CI: 1
  TETRIS_APP_PORT: 8000

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # ========================================================================
      # Setup runtimes and dependencies
      # ========================================================================
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.ci.txt
      - name: Install NodeJS dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      # ========================================================================
      # Run lints
      # ========================================================================
      - name: Lint Python source
        run: |
          ruff check --format=github --select=E9,F63,F7,F82 --target-version=py311 .
      # ========================================================================
      # Run tests
      # ========================================================================
      - name: Run UI test
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      # ========================================================================
      # Run compliance checks
      # ========================================================================
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          config-file: >-
            ./.github/dependency-review-config.yml
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python,javascript
          setup-python-dependencies: "false"
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
