name: 3. Deploy Release

on:
  release:
    types:
      - released
  workflow_dispatch: {}

concurrency:
  group: github-pages
  cancel-in-progress: false

permissions:
  contents: write
  deployments: write
  pages: write
  id-token: write

env:
  CI: true
  SITE_DIR: site

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/create-github-app-token@v1
        id: generate-app-token
        with:
          app-id: ${{ vars.APP_ID_ACTIONS_ASSISTANT }}
          private-key: ${{ secrets.APP_PRIVATE_KEY_ACTIONS_ASSISTANT }}

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Download release asset
        id: download-release-asset
        run: |
          cat << 'EOF' > event.json
          ${{ toJson(github.event) }}
          EOF
          asset_id=$(cat event.json | jq '.release.assets[] | select(.name == "${{ env.SITE_DIR }}.zip") | .id')

          curl --location --output '${{ env.SITE_DIR }}.zip'                          \
            -H "Accept: application/octet-stream"                                     \
            -H "Authorization: Bearer ${{ steps.generate-app-token.outputs.token }}"  \
            -H "X-GitHub-Api-Version: 2022-11-28"                                     \
            "https://api.github.com/repos/${{ github.repository }}/releases/assets/${asset_id}"

          unzip -o "${{ env.SITE_DIR }}.zip" -d .

          echo '##### Debug'
          ls -al "${{ env.SITE_DIR }}"

      - name: Fix site file permissions
        run: |
          chmod -c -R +rX "${{ env.SITE_DIR }}/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "${{ env.SITE_DIR }}"
          retention-days: "2"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          token: ${{ steps.generate-app-token.outputs.token }}
