# This workflow builds and tests your project and container.
# It publishes the container to GitHub Container Registry (ghcr.io).
# The published image will be tagged with the branch name.
name: Continuous Integration

on:
  pull_request:
    branches:
      - main

env:
  CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY || 'ghcr.io' }}
  CONTAINER_REGISTRY_USERNAME:
    ${{ secrets.CONTAINER_REGISTRY_USERNAME || github.actor  }}
  CONTAINER_REGISTRY_PASSWORD:
    ${{ secrets.CONTAINER_REGISTRY_PASSWORD ||  secrets.GITHUB_TOKEN }}
  POETRY_VERSION: 1.5.1
  NOX_VERSION: 2023.4.22

permissions:
  actions: read
  checks: write
  contents: read
  packages: write
  pull-requests: write
  security-events: write
  statuses: write

jobs:
  build-test-python:
    name: Build and Test Python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Poetry
        id: poetry
        run: |
          python -m pip install poetry==${{ env.POETRY_VERSION }}
          python -m pip install nox==${{ env.NOX_VERSION }}
          poetry config virtualenvs.in-project true

      - name: Cache Python Packages
        id: cache
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install Python Packages
        id: install
        run: poetry install

      - name: Dependency Review
        id: dependency-review
        uses: actions/dependency-review-action@v3
        with:
          config-file: ./.github/dependency-review-config.yml

      - name: Check Format
        id: format-check
        run: |
          nox -s format

      - name: Lint
        id: lint
        run: |
          nox -s lint

      # TODO: If needed, ensure a build script is defined.
      - name: Build
        id: build
        run: echo "No build step configured"

      - name: Test
        id: test
        run: |
          nox -s test

      - name: Report Tests
        id: report
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            reports/**/*.xml

  build-test-publish:
    name: Build, Test, and Publish
    runs-on: ubuntu-latest

    needs: build-test-python

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Build, Scan, and Publish Container Image
        id: build-scan-publish
        uses: ./.github/actions/build-scan-publish
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ env.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ env.CONTAINER_REGISTRY_PASSWORD }}
          workflow: CI

      # TODO: Add your project's test steps here
      - name: Test Container Image
        id: test
        run: echo "No tests configured"
