name: Continuous Deployment

# Run this action when PRs targeting `main` are closed.
on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    # Only run if the PR was merged.
    if: ${{ github.event.pull_request.merged == true }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: poetry

      - name: Install Dependencies
        id: install
        run: |
          pip install poetry
          poetry install

      - name: Set up Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        id: deploy
        run: |
          poetry run mkdocs gh-deploy --force --theme material
