name: Extended Checks

on:
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

jobs:
  lint-analyze-and-test-pass-02:
    uses: ./.github/workflows/continuous.integration.preliminary.yml

  app-config:
    runs-on: ubuntu-latest
    outputs:
      redis_host: ${{ steps.app-config.outputs.redis_host }}
      redis_port: ${{ steps.app-config.outputs.redis_port }}

      package_registry: ${{ steps.app-config.outputs.package_registry }}
      package_namespace: ${{ steps.app-config.outputs.package_namespace }}

      package_name_ui: ${{ steps.app-config.outputs.package_name_ui }}
      package_name_redis: ${{ steps.app-config.outputs.package_name_redis }}

      image_ui: ${{ steps.app-config.outputs.image_ui }}
      image_redis: ${{ steps.app-config.outputs.image_redis }}
    steps:
      - name: Set app configuration
        shell: bash
        run: |
          repo_owner='${{ github.event.repository.owner.login }}'
          repo_name='${{ github.event.repository.name }}'
          head_sha='${{ github.event.merge_group.head_sha }}'

          package_name="${repo_name}-${head_sha}"
          package_registry='ghcr.io'
          package_namespace="${repo_owner}"

          package_name_ui="${repo_name}-${head_sha}-ui"
          package_name_redis="${repo_name}-${head_sha}-redis"

          echo 'redis_host=localhost' >> "$GITHUB_OUTPUT"
          echo 'redis_port=6379' >> "$GITHUB_OUTPUT"

          echo "package_registry=${package_registry}" >> "$GITHUB_OUTPUT"
          echo "package_namespace=${package_namespace}" >> "$GITHUB_OUTPUT"
          echo "package_name_ui=${package_name_ui}" >> "$GITHUB_OUTPUT"
          echo "package_name_redis=${package_name_redis}" >> "$GITHUB_OUTPUT"

          echo "image_ui=${package_registry}/${package_namespace}/${package_name_ui}" >> "$GITHUB_OUTPUT"
          echo "image_redis=${package_registry}/${package_namespace}/${package_name_redis}" >> "$GITHUB_OUTPUT"
        id: app-config

  package-ui:
    needs: [app-config]
    name: Package UI
    uses: ./.github/workflows/package.yml
    with:
      package-namespace: ${{ needs.app-config.outputs.package_namespace }}
      package-registry: ${{ needs.app-config.outputs.package_registry }}
      package-name: ${{ needs.app-config.outputs.package_name_ui }}

  package-redis:
    needs: [app-config]
    name: Package Redis
    uses: ./.github/workflows/package.yml
    with:
      package-namespace: ${{ needs.app-config.outputs.package_namespace }}
      package-registry: ${{ needs.app-config.outputs.package_registry }}
      package-name: ${{ needs.app-config.outputs.package_name_redis }}

  # acceptance-tests:
  #   needs: [app-config, package-ui, package-redis]
  #   runs-on: ubuntu-latest
  #   container:
  #     image: ${{ needs.app-config.outputs.image_ui }}
  #     credentials:
  #       username: ${{ github.actor }}
  #       password: ${{ secrets.github_token }}
  #     env:
  #       REDIS_HOST: ${{ needs.app-config.outputs.redis_host }}
  #       REDIS_PORT: ${{ needs.app-config.outputs.redis_port }}
  #     ports:
  #       - 80:80
  #   services:
  #     redis:
  #       image: ${{ needs.app-config.outputs.image_redis }}
  #       ports:
  #         - ${{ needs.app-config.outputs.redis_port }}:${{ needs.app-config.outputs.redis_port }}
  #       options: >-
  #         --health-cmd "redis-cli ping"
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
