name: Package Delivery Artifacts

on:
  push:
    tags:
      - "*pre-release*"
    branches:
      - main
      - lab-2
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  package-delivery:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup GitHub Pages
      uses: actions/configure-pages@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        enablement: ture
    - name: Build GitHub Pages
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./docs
        destination: ./_site
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./_site
