# This workflow is named "Preliminary Checks"
name: Preliminary Checks

# This workflow gets triggered on pull requests to the main branch and on workflow calls
on:
  pull_request:
    branches:
      - main
  workflow_call: {}

# This workflow has read permissions for the contents
permissions:
  contents: read
  security-events: write
  actions: write

# This workflow consists of a single job named "lint-analyze-and-test-pass-01"
jobs:
  lint-analyze-and-test-pass-01:
    # This job runs on the latest version of Ubuntu
    runs-on: ubuntu-latest

    # The steps that this job will execute
    steps:
      # This step checks out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # This step sets up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # This step installs the Python dependencies needed for CI
      - name: Install CI Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # This step runs CodeQL analysis
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python

      # This step reviews the dependencies
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v3
        with:
          config-file: >-
            ./.github/dependency-review-config.yml
