name: Publish content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: squidfunk/mkdocs-material:9.4.2
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install MKDocs Extensions
        run: pip3 install --requirement ./requirements.txt
      - name: Deploy MkDocs
        run: mkdocs gh-deploy --config-file "${CONFIG_FILE}" --force --verbose
